// Code generated by MockGen. DO NOT EDIT.
// Source: build.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/traPtitech/neoshowcase/pkg/domain"
	repository "github.com/traPtitech/neoshowcase/pkg/interface/repository"
)

// MockBuildRepository is a mock of BuildRepository interface.
type MockBuildRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBuildRepositoryMockRecorder
}

// MockBuildRepositoryMockRecorder is the mock recorder for MockBuildRepository.
type MockBuildRepositoryMockRecorder struct {
	mock *MockBuildRepository
}

// NewMockBuildRepository creates a new mock instance.
func NewMockBuildRepository(ctrl *gomock.Controller) *MockBuildRepository {
	mock := &MockBuildRepository{ctrl: ctrl}
	mock.recorder = &MockBuildRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuildRepository) EXPECT() *MockBuildRepositoryMockRecorder {
	return m.recorder
}

// CreateBuild mocks base method.
func (m *MockBuildRepository) CreateBuild(ctx context.Context, applicationID string) (*domain.Build, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBuild", ctx, applicationID)
	ret0, _ := ret[0].(*domain.Build)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBuild indicates an expected call of CreateBuild.
func (mr *MockBuildRepositoryMockRecorder) CreateBuild(ctx, applicationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBuild", reflect.TypeOf((*MockBuildRepository)(nil).CreateBuild), ctx, applicationID)
}

// UpdateBuild mocks base method.
func (m *MockBuildRepository) UpdateBuild(ctx context.Context, args repository.UpdateBuildArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBuild", ctx, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBuild indicates an expected call of UpdateBuild.
func (mr *MockBuildRepositoryMockRecorder) UpdateBuild(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBuild", reflect.TypeOf((*MockBuildRepository)(nil).UpdateBuild), ctx, args)
}
