// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/traPtitech/neoshowcase/pkg/domain"
	repository "github.com/traPtitech/neoshowcase/pkg/interface/repository"
)

// MockGitrepositoryRepository is a mock of GitrepositoryRepository interface.
type MockGitrepositoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGitrepositoryRepositoryMockRecorder
}

// MockGitrepositoryRepositoryMockRecorder is the mock recorder for MockGitrepositoryRepository.
type MockGitrepositoryRepositoryMockRecorder struct {
	mock *MockGitrepositoryRepository
}

// NewMockGitrepositoryRepository creates a new mock instance.
func NewMockGitrepositoryRepository(ctrl *gomock.Controller) *MockGitrepositoryRepository {
	mock := &MockGitrepositoryRepository{ctrl: ctrl}
	mock.recorder = &MockGitrepositoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitrepositoryRepository) EXPECT() *MockGitrepositoryRepositoryMockRecorder {
	return m.recorder
}

// GetProviderByHost mocks base method.
func (m *MockGitrepositoryRepository) GetProviderByHost(ctx context.Context, host string) (*domain.Provider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProviderByHost", ctx, host)
	ret0, _ := ret[0].(*domain.Provider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProviderByHost indicates an expected call of GetProviderByHost.
func (mr *MockGitrepositoryRepositoryMockRecorder) GetProviderByHost(ctx, host interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProviderByHost", reflect.TypeOf((*MockGitrepositoryRepository)(nil).GetProviderByHost), ctx, host)
}

// GetProviderByID mocks base method.
func (m *MockGitrepositoryRepository) GetProviderByID(ctx context.Context, id string) (*domain.Provider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProviderByID", ctx, id)
	ret0, _ := ret[0].(*domain.Provider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProviderByID indicates an expected call of GetProviderByID.
func (mr *MockGitrepositoryRepositoryMockRecorder) GetProviderByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProviderByID", reflect.TypeOf((*MockGitrepositoryRepository)(nil).GetProviderByID), ctx, id)
}

// GetRepository mocks base method.
func (m *MockGitrepositoryRepository) GetRepository(ctx context.Context, args repository.GetRepositoryArgs) (*domain.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepository", ctx, args)
	ret0, _ := ret[0].(*domain.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepository indicates an expected call of GetRepository.
func (mr *MockGitrepositoryRepositoryMockRecorder) GetRepository(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepository", reflect.TypeOf((*MockGitrepositoryRepository)(nil).GetRepository), ctx, args)
}

// GetRepositoryByID mocks base method.
func (m *MockGitrepositoryRepository) GetRepositoryByID(ctx context.Context, id string) (*domain.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositoryByID", ctx, id)
	ret0, _ := ret[0].(*domain.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositoryByID indicates an expected call of GetRepositoryByID.
func (mr *MockGitrepositoryRepositoryMockRecorder) GetRepositoryByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositoryByID", reflect.TypeOf((*MockGitrepositoryRepository)(nil).GetRepositoryByID), ctx, id)
}

// RegisterProvider mocks base method.
func (m *MockGitrepositoryRepository) RegisterProvider(ctx context.Context, args repository.RegisterProviderArgs) (*domain.Provider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterProvider", ctx, args)
	ret0, _ := ret[0].(*domain.Provider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterProvider indicates an expected call of RegisterProvider.
func (mr *MockGitrepositoryRepositoryMockRecorder) RegisterProvider(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterProvider", reflect.TypeOf((*MockGitrepositoryRepository)(nil).RegisterProvider), ctx, args)
}

// RegisterRepository mocks base method.
func (m *MockGitrepositoryRepository) RegisterRepository(ctx context.Context, args repository.RegisterRepositoryArgs) (*domain.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterRepository", ctx, args)
	ret0, _ := ret[0].(*domain.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterRepository indicates an expected call of RegisterRepository.
func (mr *MockGitrepositoryRepositoryMockRecorder) RegisterRepository(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterRepository", reflect.TypeOf((*MockGitrepositoryRepository)(nil).RegisterRepository), ctx, args)
}
