kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ns-controller

rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - services
      - endpoints
      - pods
      - pods/attach
      - pods/exec
    verbs:
      - "*"
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - "*"
  - apiGroups:
      - traefik.io
      - traefik.containo.us
    resources:
      - ingressroutes
      - middlewares
    verbs:
      - "*"
