apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: victoria-metrics

spec:
  serviceName: victoria-metrics
  replicas: 1
  revisionHistoryLimit: 0
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: victoria-metrics
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
  template:
    metadata:
      labels:
        app: victoria-metrics
    spec:
      enableServiceLinks: false
      serviceAccountName: victoria-metrics
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      volumes:
        - name: config
          configMap:
            name: prometheus-config
      containers:
        - name: victoria-metrics
          image: victoriametrics/victoria-metrics:v1.91.3
          imagePullPolicy: IfNotPresent
          args:
            - --promscrape.config=/etc/config/prometheus.yml
            - --storageDataPath=/data
            - --retentionPeriod=7d
          ports:
            - containerPort: 8428
              name: http
          volumeMounts:
            - name: config
              mountPath: /etc/config
            - name: storage
              mountPath: /data
          startupProbe:
            httpGet:
              port: http
              path: /metrics
            periodSeconds: 1
            failureThreshold: 300
          readinessProbe:
            httpGet:
              port: http
              path: /metrics
            periodSeconds: 60
          livenessProbe:
            httpGet:
              port: http
              path: /metrics
            periodSeconds: 60
      terminationGracePeriodSeconds: 300
