version: "2"
linters:
  default: none
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - sloglint
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
  settings:
    sloglint:
      context: scope
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
