privateKeyFile: /keys/id_ed25519
additionalLinks:
  - name: Wiki
    url: https://wiki.trap.jp/services/NeoShowcase
  - name: Adminer
    url: http://adminer.local.trapti.tech/

db:
  host: mysql
  port: 3306
  username: root
  password: password
  database: neoshowcase

storage:
  type: local
  local:
    dir: /data

image:
  registry:
    scheme: http
    addr: registry.local
    username: ''
    password: ''
  namePrefix: ns-apps/
  tmpNamePrefix: ns-apps-tmp/

components:
  builder:
    buildkit:
      address: unix:///run/buildkit/buildkitd.sock
    buildpack:
      helper:
        address: http://buildpack:1235
        listenPort: 1235
      remoteDir: /workspace
      platformAPI: '0.11'
    controller:
      url: http://ns-controller:10000
    priority: 0
    stepTimeout: '1h'

  controller:
    port: 10000
    token: 'my-super-secret-token'
    mode: docker
    docker:
      confDir: /opt/traefik/conf
      domains:
        - domain: '*.local.trapti.tech'
          excludes: []
          auth:
            available: true
            soft:
              - nsapp_auth_soft@file
              - nsapp_auth@file
              # - ns_auth_dev@file
            hard:
              - nsapp_auth_hard@file
              - nsapp_auth@file
              # - ns_auth_dev@file
      ports:
        - startPort: 30000
          endPort: 31000
          protocol: tcp
        - startPort: 30000
          endPort: 31000
          protocol: udp

      ss:
        url: http://static-server:80/

      routing:
        type: traefik
        traefik:
          priorityOffset: 0
      middleware:
        sablier:
          enable: true
          url: http://sablier:10000
          sessionDuration: 5m
          dynamic:
            theme: neoshowcase
          blocking:
            timeout: 1m
      tls:
        certResolver: nsresolver
        wildcard:
          domains: []

      network: neoshowcase_apps
      labels:
        # test additional labels
        - key: neoshowcase.trap.jp/test
          value: ns-apps
      resources:
        cpus: 1.6
        memory: 1000000000 # 1GB
        memorySwap: -1
        memoryReservation: 256000000 # 256MB

    ssh:
      host: localhost
      port: 2201
    webhook:
      basePath: /api/webhook
      port: 8080

  gateway:
    port: 8080
    avatarBaseURL: https://q.trap.jp/api/v3/public/icon/
    authHeader: X-Showcase-User
    controller:
      url: http://ns-controller:10000
    mariadb:
      host: mysql
      port: 3306
      adminUser: root
      adminPassword: password
    mongodb:
      host: mongo
      port: 27017
      adminUser: root
      adminPassword: password
    log:
      type: loki
      loki:
        endpoint: http://loki:3100
        queryTemplate: '{ns_trap_jp_app_id="{{ .App.ID }}"}'
        logLimit: 5000
      victorialogs:
        endpoint: http://victorialogs:9428
        queryTemplate: '{ns_trap_jp_app_id="{{ .App.ID }}"}'
        logLimit: 5000
    metrics:
      type: prometheus
      prometheus:
        endpoint: http://victoria-metrics:8428
        queries:
          - name: CPU
            template: >-
              rate(container_cpu_user_seconds_total{name="nsapp-{{ .App.ID }}"}[5m])
               + rate(container_cpu_system_seconds_total{name="nsapp-{{ .App.ID }}"}[5m])
          - name: Memory
            template: >-
              container_memory_usage_bytes{name="nsapp-{{ .App.ID }}"}
               + container_memory_swap{name="nsapp-{{ .App.ID }}"}

  giteaIntegration:
    url: https://git.trap.jp
    token: ''
    controller:
      url: http://ns-controller:10000

  ssgen:
    artifactsRoot: /artifacts
    healthPort: 8081
    server:
      type: caddy
      caddy:
        adminAPI: http://static-server:2019
        docsRoot: /artifacts
    controller:
      url: http://ns-controller:10000
