// @generated by protoc-gen-connect-es v0.8.4 with parameter "target=ts"
// @generated from file neoshowcase/protobuf/apiserver.proto (package neoshowcase.protobuf, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, MethodKind } from "@bufbuild/protobuf";
import { Application, ApplicationEnvVars, ApplicationIdRequest, ApplicationOutput, ArtifactContent, ArtifactIdRequest, AvailableDomain, AvailableDomains, Build, BuildIdRequest, BuildLog, CreateApplicationRequest, CreateRepositoryRequest, GetApplicationsResponse, GetBuildsResponse, GetRepositoriesResponse, GetSystemPublicKeyResponse, Repository, RepositoryIdRequest, RetryCommitBuildRequest, SetApplicationEnvVarRequest, UpdateApplicationRequest, UpdateRepositoryRequest, User } from "./apiserver_pb.js";

/**
 * @generated from service neoshowcase.protobuf.ApplicationService
 */
export const ApplicationService = {
  typeName: "neoshowcase.protobuf.ApplicationService",
  methods: {
    /**
     * @generated from rpc neoshowcase.protobuf.ApplicationService.GetMe
     */
    getMe: {
      name: "GetMe",
      I: Empty,
      O: User,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc neoshowcase.protobuf.ApplicationService.GetRepositories
     */
    getRepositories: {
      name: "GetRepositories",
      I: Empty,
      O: GetRepositoriesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc neoshowcase.protobuf.ApplicationService.CreateRepository
     */
    createRepository: {
      name: "CreateRepository",
      I: CreateRepositoryRequest,
      O: Repository,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc neoshowcase.protobuf.ApplicationService.UpdateRepository
     */
    updateRepository: {
      name: "UpdateRepository",
      I: UpdateRepositoryRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc neoshowcase.protobuf.ApplicationService.DeleteRepository
     */
    deleteRepository: {
      name: "DeleteRepository",
      I: RepositoryIdRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc neoshowcase.protobuf.ApplicationService.GetApplications
     */
    getApplications: {
      name: "GetApplications",
      I: Empty,
      O: GetApplicationsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc neoshowcase.protobuf.ApplicationService.GetSystemPublicKey
     */
    getSystemPublicKey: {
      name: "GetSystemPublicKey",
      I: Empty,
      O: GetSystemPublicKeyResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc neoshowcase.protobuf.ApplicationService.GetAvailableDomains
     */
    getAvailableDomains: {
      name: "GetAvailableDomains",
      I: Empty,
      O: AvailableDomains,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc neoshowcase.protobuf.ApplicationService.AddAvailableDomain
     */
    addAvailableDomain: {
      name: "AddAvailableDomain",
      I: AvailableDomain,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc neoshowcase.protobuf.ApplicationService.CreateApplication
     */
    createApplication: {
      name: "CreateApplication",
      I: CreateApplicationRequest,
      O: Application,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc neoshowcase.protobuf.ApplicationService.GetApplication
     */
    getApplication: {
      name: "GetApplication",
      I: ApplicationIdRequest,
      O: Application,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc neoshowcase.protobuf.ApplicationService.UpdateApplication
     */
    updateApplication: {
      name: "UpdateApplication",
      I: UpdateApplicationRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc neoshowcase.protobuf.ApplicationService.DeleteApplication
     */
    deleteApplication: {
      name: "DeleteApplication",
      I: ApplicationIdRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc neoshowcase.protobuf.ApplicationService.GetBuilds
     */
    getBuilds: {
      name: "GetBuilds",
      I: ApplicationIdRequest,
      O: GetBuildsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc neoshowcase.protobuf.ApplicationService.GetBuild
     */
    getBuild: {
      name: "GetBuild",
      I: BuildIdRequest,
      O: Build,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc neoshowcase.protobuf.ApplicationService.GetBuildLogStream
     */
    getBuildLogStream: {
      name: "GetBuildLogStream",
      I: BuildIdRequest,
      O: BuildLog,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc neoshowcase.protobuf.ApplicationService.GetBuildLog
     */
    getBuildLog: {
      name: "GetBuildLog",
      I: BuildIdRequest,
      O: BuildLog,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc neoshowcase.protobuf.ApplicationService.GetBuildArtifact
     */
    getBuildArtifact: {
      name: "GetBuildArtifact",
      I: ArtifactIdRequest,
      O: ArtifactContent,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc neoshowcase.protobuf.ApplicationService.GetEnvVars
     */
    getEnvVars: {
      name: "GetEnvVars",
      I: ApplicationIdRequest,
      O: ApplicationEnvVars,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc neoshowcase.protobuf.ApplicationService.SetEnvVar
     */
    setEnvVar: {
      name: "SetEnvVar",
      I: SetApplicationEnvVarRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc neoshowcase.protobuf.ApplicationService.GetApplicationOutput
     */
    getApplicationOutput: {
      name: "GetApplicationOutput",
      I: ApplicationIdRequest,
      O: ApplicationOutput,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc neoshowcase.protobuf.ApplicationService.CancelBuild
     */
    cancelBuild: {
      name: "CancelBuild",
      I: BuildIdRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc neoshowcase.protobuf.ApplicationService.RetryCommitBuild
     */
    retryCommitBuild: {
      name: "RetryCommitBuild",
      I: RetryCommitBuildRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc neoshowcase.protobuf.ApplicationService.StartApplication
     */
    startApplication: {
      name: "StartApplication",
      I: ApplicationIdRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc neoshowcase.protobuf.ApplicationService.StopApplication
     */
    stopApplication: {
      name: "StopApplication",
      I: ApplicationIdRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

