apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-controller
  namespace: {{ $.Release.Namespace }}

spec:
  type: ClusterIP
  selector:
    app: {{ $.Release.Name }}-controller
  ports:
    - name: webhook
      port: 8080
      targetPort: webhook
    - name: grpc
      port: 10000
      targetPort: grpc
