kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ns-controller

rules:
  - apiGroups:
      - ""
    resources:
      - services
      - pods
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - "*"
  - apiGroups:
      - traefik.containo.us
    resources:
      - ingressroutes
      - middlewares
    verbs:
      - "*"
