// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/traPtitech/neoshowcase/pkg/infrastructure/grpc"
	"github.com/traPtitech/neoshowcase/pkg/infrastructure/repository"
	"github.com/traPtitech/neoshowcase/pkg/usecase/healthcheck"
	"github.com/traPtitech/neoshowcase/pkg/usecase/ssgen"
)

// Injectors from wire.go:

func New(c2 Config) (*Server, error) {
	config := c2.DB
	db, err := repository.New(config)
	if err != nil {
		return nil, err
	}
	controllerServiceClientConfig := c2.Controller
	controllerSSGenServiceClient := grpc.NewControllerSSGenServiceClient(controllerServiceClientConfig)
	applicationRepository := repository.NewApplicationRepository(db)
	buildRepository := repository.NewBuildRepository(db)
	storageConfig := c2.Storage
	storage, err := provideStorage(storageConfig)
	if err != nil {
		return nil, err
	}
	staticServer, err := provideStaticServer(c2)
	if err != nil {
		return nil, err
	}
	staticServerDocumentRootPath := provideStaticServerDocumentRootPath(c2)
	generatorService := ssgen.NewGeneratorService(controllerSSGenServiceClient, applicationRepository, buildRepository, storage, staticServer, staticServerDocumentRootPath)
	port := c2.HealthPort
	healthcheckFunc := provideHealthCheckFunc(generatorService)
	server := healthcheck.NewServer(port, healthcheckFunc)
	mainServer := &Server{
		db:     db,
		svc:    generatorService,
		health: server,
		engine: staticServer,
	}
	return mainServer, nil
}
