apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-ssgen
  namespace: {{ $.Release.Namespace }}

spec:
  type: ClusterIP
  selector:
    app: {{ $.Release.Name }}-ssgen
  ports:
    - name: http
      port: 80
      targetPort: http
