// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ApplicationConfig string
	ApplicationOwners string
	Applications      string
	Artifacts         string
	Builds            string
	Environments      string
	PortPublications  string
	Repositories      string
	RepositoryAuth    string
	RepositoryCommits string
	RepositoryOwners  string
	UserKeys          string
	Users             string
	Websites          string
}{
	ApplicationConfig: "application_config",
	ApplicationOwners: "application_owners",
	Applications:      "applications",
	Artifacts:         "artifacts",
	Builds:            "builds",
	Environments:      "environments",
	PortPublications:  "port_publications",
	Repositories:      "repositories",
	RepositoryAuth:    "repository_auth",
	RepositoryCommits: "repository_commits",
	RepositoryOwners:  "repository_owners",
	UserKeys:          "user_keys",
	Users:             "users",
	Websites:          "websites",
}
