// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// DynamicSiteDetail is an object representing the database table.
type DynamicSiteDetail struct {
	SiteID string `boil:"site_id" json:"site_id" toml:"site_id" yaml:"site_id"`

	R *dynamicSiteDetailR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L dynamicSiteDetailL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var DynamicSiteDetailColumns = struct {
	SiteID string
}{
	SiteID: "site_id",
}

// Generated where

var DynamicSiteDetailWhere = struct {
	SiteID whereHelperstring
}{
	SiteID: whereHelperstring{field: "`dynamic_site_details`.`site_id`"},
}

// DynamicSiteDetailRels is where relationship names are stored.
var DynamicSiteDetailRels = struct {
	Site string
}{
	Site: "Site",
}

// dynamicSiteDetailR is where relationships are stored.
type dynamicSiteDetailR struct {
	Site *Site `boil:"Site" json:"Site" toml:"Site" yaml:"Site"`
}

// NewStruct creates a new relationship struct
func (*dynamicSiteDetailR) NewStruct() *dynamicSiteDetailR {
	return &dynamicSiteDetailR{}
}

// dynamicSiteDetailL is where Load methods for each relationship are stored.
type dynamicSiteDetailL struct{}

var (
	dynamicSiteDetailAllColumns            = []string{"site_id"}
	dynamicSiteDetailColumnsWithoutDefault = []string{"site_id"}
	dynamicSiteDetailColumnsWithDefault    = []string{}
	dynamicSiteDetailPrimaryKeyColumns     = []string{"site_id"}
)

type (
	// DynamicSiteDetailSlice is an alias for a slice of pointers to DynamicSiteDetail.
	// This should generally be used opposed to []DynamicSiteDetail.
	DynamicSiteDetailSlice []*DynamicSiteDetail
	// DynamicSiteDetailHook is the signature for custom DynamicSiteDetail hook methods
	DynamicSiteDetailHook func(context.Context, boil.ContextExecutor, *DynamicSiteDetail) error

	dynamicSiteDetailQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	dynamicSiteDetailType                 = reflect.TypeOf(&DynamicSiteDetail{})
	dynamicSiteDetailMapping              = queries.MakeStructMapping(dynamicSiteDetailType)
	dynamicSiteDetailPrimaryKeyMapping, _ = queries.BindMapping(dynamicSiteDetailType, dynamicSiteDetailMapping, dynamicSiteDetailPrimaryKeyColumns)
	dynamicSiteDetailInsertCacheMut       sync.RWMutex
	dynamicSiteDetailInsertCache          = make(map[string]insertCache)
	dynamicSiteDetailUpdateCacheMut       sync.RWMutex
	dynamicSiteDetailUpdateCache          = make(map[string]updateCache)
	dynamicSiteDetailUpsertCacheMut       sync.RWMutex
	dynamicSiteDetailUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var dynamicSiteDetailBeforeInsertHooks []DynamicSiteDetailHook
var dynamicSiteDetailBeforeUpdateHooks []DynamicSiteDetailHook
var dynamicSiteDetailBeforeDeleteHooks []DynamicSiteDetailHook
var dynamicSiteDetailBeforeUpsertHooks []DynamicSiteDetailHook

var dynamicSiteDetailAfterInsertHooks []DynamicSiteDetailHook
var dynamicSiteDetailAfterSelectHooks []DynamicSiteDetailHook
var dynamicSiteDetailAfterUpdateHooks []DynamicSiteDetailHook
var dynamicSiteDetailAfterDeleteHooks []DynamicSiteDetailHook
var dynamicSiteDetailAfterUpsertHooks []DynamicSiteDetailHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *DynamicSiteDetail) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dynamicSiteDetailBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *DynamicSiteDetail) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dynamicSiteDetailBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *DynamicSiteDetail) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dynamicSiteDetailBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *DynamicSiteDetail) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dynamicSiteDetailBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *DynamicSiteDetail) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dynamicSiteDetailAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *DynamicSiteDetail) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dynamicSiteDetailAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *DynamicSiteDetail) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dynamicSiteDetailAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *DynamicSiteDetail) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dynamicSiteDetailAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *DynamicSiteDetail) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dynamicSiteDetailAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddDynamicSiteDetailHook registers your hook function for all future operations.
func AddDynamicSiteDetailHook(hookPoint boil.HookPoint, dynamicSiteDetailHook DynamicSiteDetailHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		dynamicSiteDetailBeforeInsertHooks = append(dynamicSiteDetailBeforeInsertHooks, dynamicSiteDetailHook)
	case boil.BeforeUpdateHook:
		dynamicSiteDetailBeforeUpdateHooks = append(dynamicSiteDetailBeforeUpdateHooks, dynamicSiteDetailHook)
	case boil.BeforeDeleteHook:
		dynamicSiteDetailBeforeDeleteHooks = append(dynamicSiteDetailBeforeDeleteHooks, dynamicSiteDetailHook)
	case boil.BeforeUpsertHook:
		dynamicSiteDetailBeforeUpsertHooks = append(dynamicSiteDetailBeforeUpsertHooks, dynamicSiteDetailHook)
	case boil.AfterInsertHook:
		dynamicSiteDetailAfterInsertHooks = append(dynamicSiteDetailAfterInsertHooks, dynamicSiteDetailHook)
	case boil.AfterSelectHook:
		dynamicSiteDetailAfterSelectHooks = append(dynamicSiteDetailAfterSelectHooks, dynamicSiteDetailHook)
	case boil.AfterUpdateHook:
		dynamicSiteDetailAfterUpdateHooks = append(dynamicSiteDetailAfterUpdateHooks, dynamicSiteDetailHook)
	case boil.AfterDeleteHook:
		dynamicSiteDetailAfterDeleteHooks = append(dynamicSiteDetailAfterDeleteHooks, dynamicSiteDetailHook)
	case boil.AfterUpsertHook:
		dynamicSiteDetailAfterUpsertHooks = append(dynamicSiteDetailAfterUpsertHooks, dynamicSiteDetailHook)
	}
}

// One returns a single dynamicSiteDetail record from the query.
func (q dynamicSiteDetailQuery) One(ctx context.Context, exec boil.ContextExecutor) (*DynamicSiteDetail, error) {
	o := &DynamicSiteDetail{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for dynamic_site_details")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all DynamicSiteDetail records from the query.
func (q dynamicSiteDetailQuery) All(ctx context.Context, exec boil.ContextExecutor) (DynamicSiteDetailSlice, error) {
	var o []*DynamicSiteDetail

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to DynamicSiteDetail slice")
	}

	if len(dynamicSiteDetailAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all DynamicSiteDetail records in the query.
func (q dynamicSiteDetailQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count dynamic_site_details rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q dynamicSiteDetailQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if dynamic_site_details exists")
	}

	return count > 0, nil
}

// Site pointed to by the foreign key.
func (o *DynamicSiteDetail) Site(mods ...qm.QueryMod) siteQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.SiteID),
	}

	queryMods = append(queryMods, mods...)

	query := Sites(queryMods...)
	queries.SetFrom(query.Query, "`sites`")

	return query
}

// LoadSite allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (dynamicSiteDetailL) LoadSite(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDynamicSiteDetail interface{}, mods queries.Applicator) error {
	var slice []*DynamicSiteDetail
	var object *DynamicSiteDetail

	if singular {
		object = maybeDynamicSiteDetail.(*DynamicSiteDetail)
	} else {
		slice = *maybeDynamicSiteDetail.(*[]*DynamicSiteDetail)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &dynamicSiteDetailR{}
		}
		args = append(args, object.SiteID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &dynamicSiteDetailR{}
			}

			for _, a := range args {
				if a == obj.SiteID {
					continue Outer
				}
			}

			args = append(args, obj.SiteID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`sites`),
		qm.WhereIn(`sites.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Site")
	}

	var resultSlice []*Site
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Site")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for sites")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for sites")
	}

	if len(dynamicSiteDetailAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Site = foreign
		if foreign.R == nil {
			foreign.R = &siteR{}
		}
		foreign.R.DynamicSiteDetail = object
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.SiteID == foreign.ID {
				local.R.Site = foreign
				if foreign.R == nil {
					foreign.R = &siteR{}
				}
				foreign.R.DynamicSiteDetail = local
				break
			}
		}
	}

	return nil
}

// SetSite of the dynamicSiteDetail to the related item.
// Sets o.R.Site to related.
// Adds o to related.R.DynamicSiteDetail.
func (o *DynamicSiteDetail) SetSite(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Site) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `dynamic_site_details` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"site_id"}),
		strmangle.WhereClause("`", "`", 0, dynamicSiteDetailPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.SiteID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.SiteID = related.ID
	if o.R == nil {
		o.R = &dynamicSiteDetailR{
			Site: related,
		}
	} else {
		o.R.Site = related
	}

	if related.R == nil {
		related.R = &siteR{
			DynamicSiteDetail: o,
		}
	} else {
		related.R.DynamicSiteDetail = o
	}

	return nil
}

// DynamicSiteDetails retrieves all the records using an executor.
func DynamicSiteDetails(mods ...qm.QueryMod) dynamicSiteDetailQuery {
	mods = append(mods, qm.From("`dynamic_site_details`"))
	return dynamicSiteDetailQuery{NewQuery(mods...)}
}

// FindDynamicSiteDetail retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindDynamicSiteDetail(ctx context.Context, exec boil.ContextExecutor, siteID string, selectCols ...string) (*DynamicSiteDetail, error) {
	dynamicSiteDetailObj := &DynamicSiteDetail{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `dynamic_site_details` where `site_id`=?", sel,
	)

	q := queries.Raw(query, siteID)

	err := q.Bind(ctx, exec, dynamicSiteDetailObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from dynamic_site_details")
	}

	return dynamicSiteDetailObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *DynamicSiteDetail) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no dynamic_site_details provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(dynamicSiteDetailColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	dynamicSiteDetailInsertCacheMut.RLock()
	cache, cached := dynamicSiteDetailInsertCache[key]
	dynamicSiteDetailInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			dynamicSiteDetailAllColumns,
			dynamicSiteDetailColumnsWithDefault,
			dynamicSiteDetailColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(dynamicSiteDetailType, dynamicSiteDetailMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(dynamicSiteDetailType, dynamicSiteDetailMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `dynamic_site_details` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `dynamic_site_details` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `dynamic_site_details` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, dynamicSiteDetailPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into dynamic_site_details")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.SiteID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for dynamic_site_details")
	}

CacheNoHooks:
	if !cached {
		dynamicSiteDetailInsertCacheMut.Lock()
		dynamicSiteDetailInsertCache[key] = cache
		dynamicSiteDetailInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the DynamicSiteDetail.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *DynamicSiteDetail) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	dynamicSiteDetailUpdateCacheMut.RLock()
	cache, cached := dynamicSiteDetailUpdateCache[key]
	dynamicSiteDetailUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			dynamicSiteDetailAllColumns,
			dynamicSiteDetailPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update dynamic_site_details, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `dynamic_site_details` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, dynamicSiteDetailPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(dynamicSiteDetailType, dynamicSiteDetailMapping, append(wl, dynamicSiteDetailPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update dynamic_site_details row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for dynamic_site_details")
	}

	if !cached {
		dynamicSiteDetailUpdateCacheMut.Lock()
		dynamicSiteDetailUpdateCache[key] = cache
		dynamicSiteDetailUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q dynamicSiteDetailQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for dynamic_site_details")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for dynamic_site_details")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o DynamicSiteDetailSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), dynamicSiteDetailPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `dynamic_site_details` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, dynamicSiteDetailPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in dynamicSiteDetail slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all dynamicSiteDetail")
	}
	return rowsAff, nil
}

var mySQLDynamicSiteDetailUniqueColumns = []string{
	"site_id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *DynamicSiteDetail) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no dynamic_site_details provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(dynamicSiteDetailColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLDynamicSiteDetailUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	dynamicSiteDetailUpsertCacheMut.RLock()
	cache, cached := dynamicSiteDetailUpsertCache[key]
	dynamicSiteDetailUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			dynamicSiteDetailAllColumns,
			dynamicSiteDetailColumnsWithDefault,
			dynamicSiteDetailColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			dynamicSiteDetailAllColumns,
			dynamicSiteDetailPrimaryKeyColumns,
		)

		if len(update) == 0 {
			return errors.New("models: unable to upsert dynamic_site_details, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "dynamic_site_details", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `dynamic_site_details` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(dynamicSiteDetailType, dynamicSiteDetailMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(dynamicSiteDetailType, dynamicSiteDetailMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for dynamic_site_details")
	}

	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(dynamicSiteDetailType, dynamicSiteDetailMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for dynamic_site_details")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for dynamic_site_details")
	}

CacheNoHooks:
	if !cached {
		dynamicSiteDetailUpsertCacheMut.Lock()
		dynamicSiteDetailUpsertCache[key] = cache
		dynamicSiteDetailUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single DynamicSiteDetail record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *DynamicSiteDetail) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no DynamicSiteDetail provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), dynamicSiteDetailPrimaryKeyMapping)
	sql := "DELETE FROM `dynamic_site_details` WHERE `site_id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from dynamic_site_details")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for dynamic_site_details")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q dynamicSiteDetailQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no dynamicSiteDetailQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from dynamic_site_details")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for dynamic_site_details")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o DynamicSiteDetailSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(dynamicSiteDetailBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), dynamicSiteDetailPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `dynamic_site_details` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, dynamicSiteDetailPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from dynamicSiteDetail slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for dynamic_site_details")
	}

	if len(dynamicSiteDetailAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *DynamicSiteDetail) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindDynamicSiteDetail(ctx, exec, o.SiteID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *DynamicSiteDetailSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := DynamicSiteDetailSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), dynamicSiteDetailPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `dynamic_site_details`.* FROM `dynamic_site_details` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, dynamicSiteDetailPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in DynamicSiteDetailSlice")
	}

	*o = slice

	return nil
}

// DynamicSiteDetailExists checks if the DynamicSiteDetail row exists.
func DynamicSiteDetailExists(ctx context.Context, exec boil.ContextExecutor, siteID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `dynamic_site_details` where `site_id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, siteID)
	}
	row := exec.QueryRowContext(ctx, sql, siteID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if dynamic_site_details exists")
	}

	return exists, nil
}
