// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testStaticSiteDetails(t *testing.T) {
	t.Parallel()

	query := StaticSiteDetails()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testStaticSiteDetailsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StaticSiteDetail{}
	if err = randomize.Struct(seed, o, staticSiteDetailDBTypes, true, staticSiteDetailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StaticSiteDetail struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := StaticSiteDetails().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testStaticSiteDetailsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StaticSiteDetail{}
	if err = randomize.Struct(seed, o, staticSiteDetailDBTypes, true, staticSiteDetailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StaticSiteDetail struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := StaticSiteDetails().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := StaticSiteDetails().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testStaticSiteDetailsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StaticSiteDetail{}
	if err = randomize.Struct(seed, o, staticSiteDetailDBTypes, true, staticSiteDetailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StaticSiteDetail struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := StaticSiteDetailSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := StaticSiteDetails().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testStaticSiteDetailsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StaticSiteDetail{}
	if err = randomize.Struct(seed, o, staticSiteDetailDBTypes, true, staticSiteDetailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StaticSiteDetail struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := StaticSiteDetailExists(ctx, tx, o.SiteID)
	if err != nil {
		t.Errorf("Unable to check if StaticSiteDetail exists: %s", err)
	}
	if !e {
		t.Errorf("Expected StaticSiteDetailExists to return true, but got false.")
	}
}

func testStaticSiteDetailsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StaticSiteDetail{}
	if err = randomize.Struct(seed, o, staticSiteDetailDBTypes, true, staticSiteDetailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StaticSiteDetail struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	staticSiteDetailFound, err := FindStaticSiteDetail(ctx, tx, o.SiteID)
	if err != nil {
		t.Error(err)
	}

	if staticSiteDetailFound == nil {
		t.Error("want a record, got nil")
	}
}

func testStaticSiteDetailsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StaticSiteDetail{}
	if err = randomize.Struct(seed, o, staticSiteDetailDBTypes, true, staticSiteDetailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StaticSiteDetail struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = StaticSiteDetails().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testStaticSiteDetailsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StaticSiteDetail{}
	if err = randomize.Struct(seed, o, staticSiteDetailDBTypes, true, staticSiteDetailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StaticSiteDetail struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := StaticSiteDetails().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testStaticSiteDetailsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	staticSiteDetailOne := &StaticSiteDetail{}
	staticSiteDetailTwo := &StaticSiteDetail{}
	if err = randomize.Struct(seed, staticSiteDetailOne, staticSiteDetailDBTypes, false, staticSiteDetailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StaticSiteDetail struct: %s", err)
	}
	if err = randomize.Struct(seed, staticSiteDetailTwo, staticSiteDetailDBTypes, false, staticSiteDetailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StaticSiteDetail struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = staticSiteDetailOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = staticSiteDetailTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := StaticSiteDetails().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testStaticSiteDetailsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	staticSiteDetailOne := &StaticSiteDetail{}
	staticSiteDetailTwo := &StaticSiteDetail{}
	if err = randomize.Struct(seed, staticSiteDetailOne, staticSiteDetailDBTypes, false, staticSiteDetailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StaticSiteDetail struct: %s", err)
	}
	if err = randomize.Struct(seed, staticSiteDetailTwo, staticSiteDetailDBTypes, false, staticSiteDetailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StaticSiteDetail struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = staticSiteDetailOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = staticSiteDetailTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := StaticSiteDetails().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func staticSiteDetailBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *StaticSiteDetail) error {
	*o = StaticSiteDetail{}
	return nil
}

func staticSiteDetailAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *StaticSiteDetail) error {
	*o = StaticSiteDetail{}
	return nil
}

func staticSiteDetailAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *StaticSiteDetail) error {
	*o = StaticSiteDetail{}
	return nil
}

func staticSiteDetailBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *StaticSiteDetail) error {
	*o = StaticSiteDetail{}
	return nil
}

func staticSiteDetailAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *StaticSiteDetail) error {
	*o = StaticSiteDetail{}
	return nil
}

func staticSiteDetailBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *StaticSiteDetail) error {
	*o = StaticSiteDetail{}
	return nil
}

func staticSiteDetailAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *StaticSiteDetail) error {
	*o = StaticSiteDetail{}
	return nil
}

func staticSiteDetailBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *StaticSiteDetail) error {
	*o = StaticSiteDetail{}
	return nil
}

func staticSiteDetailAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *StaticSiteDetail) error {
	*o = StaticSiteDetail{}
	return nil
}

func testStaticSiteDetailsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &StaticSiteDetail{}
	o := &StaticSiteDetail{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, staticSiteDetailDBTypes, false); err != nil {
		t.Errorf("Unable to randomize StaticSiteDetail object: %s", err)
	}

	AddStaticSiteDetailHook(boil.BeforeInsertHook, staticSiteDetailBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	staticSiteDetailBeforeInsertHooks = []StaticSiteDetailHook{}

	AddStaticSiteDetailHook(boil.AfterInsertHook, staticSiteDetailAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	staticSiteDetailAfterInsertHooks = []StaticSiteDetailHook{}

	AddStaticSiteDetailHook(boil.AfterSelectHook, staticSiteDetailAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	staticSiteDetailAfterSelectHooks = []StaticSiteDetailHook{}

	AddStaticSiteDetailHook(boil.BeforeUpdateHook, staticSiteDetailBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	staticSiteDetailBeforeUpdateHooks = []StaticSiteDetailHook{}

	AddStaticSiteDetailHook(boil.AfterUpdateHook, staticSiteDetailAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	staticSiteDetailAfterUpdateHooks = []StaticSiteDetailHook{}

	AddStaticSiteDetailHook(boil.BeforeDeleteHook, staticSiteDetailBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	staticSiteDetailBeforeDeleteHooks = []StaticSiteDetailHook{}

	AddStaticSiteDetailHook(boil.AfterDeleteHook, staticSiteDetailAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	staticSiteDetailAfterDeleteHooks = []StaticSiteDetailHook{}

	AddStaticSiteDetailHook(boil.BeforeUpsertHook, staticSiteDetailBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	staticSiteDetailBeforeUpsertHooks = []StaticSiteDetailHook{}

	AddStaticSiteDetailHook(boil.AfterUpsertHook, staticSiteDetailAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	staticSiteDetailAfterUpsertHooks = []StaticSiteDetailHook{}
}

func testStaticSiteDetailsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StaticSiteDetail{}
	if err = randomize.Struct(seed, o, staticSiteDetailDBTypes, true, staticSiteDetailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StaticSiteDetail struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := StaticSiteDetails().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testStaticSiteDetailsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StaticSiteDetail{}
	if err = randomize.Struct(seed, o, staticSiteDetailDBTypes, true); err != nil {
		t.Errorf("Unable to randomize StaticSiteDetail struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(staticSiteDetailColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := StaticSiteDetails().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testStaticSiteDetailToOneArtifactUsingArtifact(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local StaticSiteDetail
	var foreign Artifact

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, staticSiteDetailDBTypes, true, staticSiteDetailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StaticSiteDetail struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, artifactDBTypes, false, artifactColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Artifact struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.ArtifactID, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Artifact().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := StaticSiteDetailSlice{&local}
	if err = local.L.LoadArtifact(ctx, tx, false, (*[]*StaticSiteDetail)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Artifact == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Artifact = nil
	if err = local.L.LoadArtifact(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Artifact == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testStaticSiteDetailToOneSiteUsingSite(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local StaticSiteDetail
	var foreign Site

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, staticSiteDetailDBTypes, false, staticSiteDetailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StaticSiteDetail struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, siteDBTypes, false, siteColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Site struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.SiteID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Site().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := StaticSiteDetailSlice{&local}
	if err = local.L.LoadSite(ctx, tx, false, (*[]*StaticSiteDetail)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Site == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Site = nil
	if err = local.L.LoadSite(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Site == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testStaticSiteDetailToOneSetOpArtifactUsingArtifact(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a StaticSiteDetail
	var b, c Artifact

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, staticSiteDetailDBTypes, false, strmangle.SetComplement(staticSiteDetailPrimaryKeyColumns, staticSiteDetailColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, artifactDBTypes, false, strmangle.SetComplement(artifactPrimaryKeyColumns, artifactColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, artifactDBTypes, false, strmangle.SetComplement(artifactPrimaryKeyColumns, artifactColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Artifact{&b, &c} {
		err = a.SetArtifact(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Artifact != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.StaticSiteDetails[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.ArtifactID, x.ID) {
			t.Error("foreign key was wrong value", a.ArtifactID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.ArtifactID))
		reflect.Indirect(reflect.ValueOf(&a.ArtifactID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.ArtifactID, x.ID) {
			t.Error("foreign key was wrong value", a.ArtifactID, x.ID)
		}
	}
}

func testStaticSiteDetailToOneRemoveOpArtifactUsingArtifact(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a StaticSiteDetail
	var b Artifact

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, staticSiteDetailDBTypes, false, strmangle.SetComplement(staticSiteDetailPrimaryKeyColumns, staticSiteDetailColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, artifactDBTypes, false, strmangle.SetComplement(artifactPrimaryKeyColumns, artifactColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetArtifact(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveArtifact(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.Artifact().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.Artifact != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.ArtifactID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.StaticSiteDetails) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testStaticSiteDetailToOneSetOpSiteUsingSite(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a StaticSiteDetail
	var b, c Site

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, staticSiteDetailDBTypes, false, strmangle.SetComplement(staticSiteDetailPrimaryKeyColumns, staticSiteDetailColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, siteDBTypes, false, strmangle.SetComplement(sitePrimaryKeyColumns, siteColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, siteDBTypes, false, strmangle.SetComplement(sitePrimaryKeyColumns, siteColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Site{&b, &c} {
		err = a.SetSite(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Site != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.StaticSiteDetail != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.SiteID != x.ID {
			t.Error("foreign key was wrong value", a.SiteID)
		}

		if exists, err := StaticSiteDetailExists(ctx, tx, a.SiteID); err != nil {
			t.Fatal(err)
		} else if !exists {
			t.Error("want 'a' to exist")
		}

	}
}

func testStaticSiteDetailsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StaticSiteDetail{}
	if err = randomize.Struct(seed, o, staticSiteDetailDBTypes, true, staticSiteDetailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StaticSiteDetail struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testStaticSiteDetailsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StaticSiteDetail{}
	if err = randomize.Struct(seed, o, staticSiteDetailDBTypes, true, staticSiteDetailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StaticSiteDetail struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := StaticSiteDetailSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testStaticSiteDetailsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StaticSiteDetail{}
	if err = randomize.Struct(seed, o, staticSiteDetailDBTypes, true, staticSiteDetailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StaticSiteDetail struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := StaticSiteDetails().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	staticSiteDetailDBTypes = map[string]string{`SiteID`: `varchar`, `ArtifactID`: `varchar`}
	_                       = bytes.MinRead
)

func testStaticSiteDetailsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(staticSiteDetailPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(staticSiteDetailAllColumns) == len(staticSiteDetailPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &StaticSiteDetail{}
	if err = randomize.Struct(seed, o, staticSiteDetailDBTypes, true, staticSiteDetailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StaticSiteDetail struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := StaticSiteDetails().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, staticSiteDetailDBTypes, true, staticSiteDetailPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize StaticSiteDetail struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testStaticSiteDetailsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(staticSiteDetailAllColumns) == len(staticSiteDetailPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &StaticSiteDetail{}
	if err = randomize.Struct(seed, o, staticSiteDetailDBTypes, true, staticSiteDetailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StaticSiteDetail struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := StaticSiteDetails().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, staticSiteDetailDBTypes, true, staticSiteDetailPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize StaticSiteDetail struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(staticSiteDetailAllColumns, staticSiteDetailPrimaryKeyColumns) {
		fields = staticSiteDetailAllColumns
	} else {
		fields = strmangle.SetComplement(
			staticSiteDetailAllColumns,
			staticSiteDetailPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := StaticSiteDetailSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testStaticSiteDetailsUpsert(t *testing.T) {
	t.Parallel()

	if len(staticSiteDetailAllColumns) == len(staticSiteDetailPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLStaticSiteDetailUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := StaticSiteDetail{}
	if err = randomize.Struct(seed, &o, staticSiteDetailDBTypes, false); err != nil {
		t.Errorf("Unable to randomize StaticSiteDetail struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert StaticSiteDetail: %s", err)
	}

	count, err := StaticSiteDetails().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, staticSiteDetailDBTypes, false, staticSiteDetailPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize StaticSiteDetail struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert StaticSiteDetail: %s", err)
	}

	count, err = StaticSiteDetails().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
