apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: victoria-metrics

spec:
  serviceName: victoria-metrics
  replicas: 1
  selector:
    matchLabels:
      app: victoria-metrics

  template:
    metadata:
      labels:
        app: victoria-metrics
    spec:
      enableServiceLinks: false
      serviceAccountName: victoria-metrics

      volumes:
        - name: config
          configMap:
            name: prometheus-config
        - name: project
          hostPath:
            path: /work

      containers:
        - name: victoria-metrics
          image: victoriametrics/victoria-metrics:v1.102.1
          imagePullPolicy: IfNotPresent
          args:
            - --promscrape.config=/etc/config/prometheus.yml
            - --promscrape.maxScrapeSize=256MB
            - --maxLabelsPerTimeseries=128
            - --storageDataPath=/data
            - --retentionPeriod=7d
          ports:
            - name: http
              containerPort: 8428
          volumeMounts:
            - name: config
              mountPath: /etc/config
            - name: project
              subPath: .local-dev/victoria-metrics
              mountPath: /data
