resources:
  # ls components/*.yaml | sed -e 's/^/ - /g'
  - components/builder-deployment.yaml
  - components/builder-role-binding.yaml
  - components/builder-role.yaml
  - components/builder-service-account.yaml
  - components/controller-role-binding.yaml
  - components/controller-role.yaml
  - components/controller-service-account.yaml
  - components/controller-service.yaml
  - components/controller-stateful-set.yaml
  - components/dashboard-deployment.yaml
  - components/dashboard-service.yaml
  - components/gateway-deployment.yaml
  - components/gateway-service.yaml
  - components/ingress-route.yaml
  - components/ssgen-deployment.yaml
  - components/ssgen-service.yaml
  - components/ssh-ingress-route.yaml
  # ls services/*.yaml | sed -e 's/^/ - /g'
  - services/adminer-deployment.yaml
  - services/adminer-ingress-route.yaml
  - services/adminer-service.yaml
  - services/mariadb-service.yaml
  - services/mariadb-stateful-set.yaml
  - services/minio-deployment.yaml
  - services/minio-ingress-route.yaml
  - services/minio-service.yaml
  - services/mongo-service.yaml
  - services/mongo-stateful-set.yaml
  - services/ns-auth-deployment.yaml
  - services/ns-auth-dev-deployment.yaml
  - services/ns-auth-dev-middleware.yaml
  - services/ns-auth-dev-service.yaml
  - services/ns-auth-middleware.yaml
  - services/ns-auth-service.yaml
  - services/registry-deployment.yaml
  - services/registry-frontend-deployment.yaml
  - services/registry-frontend-ingress-route.yaml
  - services/registry-frontend-service.yaml
  - services/registry-ingress-route.yaml
  - services/registry-service.yaml
  - mariadb-migration-workflow-template.yaml

configMapGenerator:
  - name: ns-config
    files:
      - config/buildkitd.toml
      - config/ns.yaml
      - config/ns-auth.ini
    literals:
      - MariaDBHost=mariadb.ns-system.svc.cluster.local
      - MariaDBPort=3306
      - MariaDBUser=root
      - MariaDBPassword=password
      - MariaDBName=neoshowcase
      - MongoUser=root
      - MongoPassword=password
  - name: registry-config
    files:
      - config/registry/entrypoint.sh
      - config/registry/gc.sh

secretGenerator:
  - name: ns-keys
    files:
      - config/id_ed25519

configurations:
  - kustomize-config.yaml
