apiVersion: apps/v1
kind: Deployment
metadata:
  name: sablier
  labels:
    app: sablier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sablier
  template:
    metadata:
      labels:
        app: sablier
    spec:
      serviceAccountName: sablier
      volumes:
        - name: project
          hostPath:
            path: /work
      containers:
        - name: sablier
          image: acouvreur/sablier:1.7.0
          ports:
            - name: http
              containerPort: 10000
          volumeMounts:
            - name: project
              subPath: .local-dev/config/sablier.yaml
              mountPath: /etc/sablier/sablier.yaml
