{{- with $.Values.sablier }}
{{- if .enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-sablier
  namespace: {{ $.Release.Namespace }}

spec:
  type: ClusterIP
  selector:
    app: {{ $.Release.Name }}-sablier
  ports:
    - name: http
      port: 80
      targetPort: http

{{- end }}
{{- end }}
