privateKeyFile: /keys/id_ed25519
adminerURL: http://adminer.local.trapti.tech/

db:
  host: mariadb.ns-system.svc.cluster.local
  port: 3306
  username: root
  password: password
  database: neoshowcase

storage:
  type: s3
  s3:
    bucket: neoshowcase
    accessKey: NEOSHOWCASEMINIOROOTUSER
    accessSecret: 593fbde300c5718e416886e7e4be339d903541b3900f211ceb89f5b4052a98b3
    region: us-east-1
    endpoint: http://minio.ns-system.svc.cluster.local

image:
  registry:
    scheme: http
    addr: registry.ns-system.svc.cluster.local
    username: ""
    password: ""
  namePrefix: ns-apps/
  tmpNamePrefix: ns-apps-tmp/

components:
  builder:
    buildkit:
      address: unix:///run/buildkit/buildkitd.sock
    buildpack:
      backend: k8s
      k8s:
        namespace: ns-system
        # podName: ns-builder # specified from env
        containerName: buildpack
        localDir: /neoshowcase/buildpack
        remoteDir: /workspace
        user: 1001
        group: 1000
        platformAPI: "0.11"
    controller:
      url: http://ns-controller.ns-system.svc.cluster.local:10000

  controller:
    port: 10000
    mode: k8s
    k8s:
      domains:
        - domain: "*.local.trapti.tech"
          excludes: []
          auth:
            available: true
            soft:
              - name: nsapp-auth-soft
                namespace: ns-apps
              - name: nsapp-auth
                namespace: ns-apps
            hard:
              - name: nsapp-auth-hard
                namespace: ns-apps
              - name: nsapp-auth
                namespace: ns-apps
      ports:
        - startPort: 39000
          endPort: 39999
          protocol: tcp
        - startPort: 39000
          endPort: 39999
          protocol: udp
      ss:
        namespace: ns-system
        kind: Service
        name: ns-ssgen
        port: 80
        scheme: http
      namespace: ns-apps
      # extra labels
      labels:
        - key: app.kubernetes.io/instance
          value: ns-apps
      tls:
        type: traefik
        traefik:
          certResolver: resolver
          wildcard:
            domains: []
      # required if registry is private
      imagePullSecret: ""
      resources:
        requests:
          cpu: 10m
          memory: 50M
        limits:
          cpu: 1600m
          memory: 1G
    ssh:
      host: localhost
      port: 2201
    webhook:
      basePath: /api/webhook
      port: 8080

  gateway:
    port: 8080
    avatarBaseURL: https://q.trap.jp/api/v3/public/icon/
    headerName: X-Showcase-User
    controller:
      url: http://ns-controller.ns-system.svc.cluster.local:10000
    mariadb:
      host: mariadb.ns-system.svc.cluster.local
      port: 3306
      adminUser: root
      adminPassword: password
    mongodb:
      host: mongo
      port: 27017
      adminUser: root
      adminPassword: password
    log:
      type: loki
      loki:
        endpoint: http://loki.loki.svc.cluster.local:3100
        queryTemplate: "{ns_trap_jp_app_id=\"{{ .App.ID }}\"}"
    metrics:
      type: prometheus
      prometheus:
        endpoint: http://victoria-metrics.victoria-metrics.svc.cluster.local
        queries:
          - name: CPU
            template: >-
              rate(container_cpu_user_seconds_total{namespace="ns-apps", pod="nsapp-{{ .App.ID }}-0", container="app"}[5m])
               + rate(container_cpu_system_seconds_total{namespace="ns-apps", pod="nsapp-{{ .App.ID }}-0", container="app"}[5m])
          - name: Memory
            template: >-
              container_memory_usage_bytes{namespace="ns-apps", pod="nsapp-{{ .App.ID }}-0", container="app"}
               + container_memory_swap{namespace="ns-apps", pod="nsapp-{{ .App.ID }}-0", container="app"}

  ssgen:
    artifactsRoot: /artifacts
    healthPort: 8081
    server:
      type: builtIn
      builtIn:
        port: 80
    controller:
      url: http://ns-controller.ns-system.svc.cluster.local:10000

