name: Protobuf CI

on:
  push:
    branches:
      - "main"
    paths:
      - "api/**"
  pull_request:
    paths:
      - "api/**"

jobs:
  gen-diff:
    name: Check diff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
        with:
          install_args: buf
      - name: Generate code
        run: mise run gen:proto
      - name: Check diff
        run: git diff --exit-code

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
        with:
          install_args: buf
      - name: Format proto files
        run: |
          if ! buf format --diff --exit-code; then
            echo "::error::Run 'buf format -w' to fix"
            exit 1
          fi

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
        with:
          install_args: buf
      - name: Lint proto files
        run: buf lint
