name: Preview

on:
  pull_request:

permissions:
  packages: write

jobs:
  image:
    name: Build preview images
    runs-on: ubuntu-latest
    steps:
      - name: Set PR_NUMBER env
        run: echo "PR_NUMBER=${{ github.event.number }}" >> $GITHUB_ENV

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: echo "APP_VERSION=preview-${{ env.PR_NUMBER }}" >> $GITHUB_ENV
      - run: echo "APP_REVISION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0
      - uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
        id: buildx
      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: traptitech
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          # TODO: Remove longer tag name and use type=sha in ArgoCD ApplicationSet Generator
          tags: |
            type=sha
            type=raw,value=preview-${{ env.PR_NUMBER }}-${{ github.event.pull_request.head.sha }}
          sep-tags: ","

      - name: Build
        uses: docker/bake-action@a66e1c87e2eca0503c343edf1d208c716d54b8a8 # v7.1.0
        env:
          APP_VERSION: ${{ env.APP_VERSION }}
          APP_REVISION: ${{ env.APP_REVISION }}
          TAGS: ${{ steps.meta.outputs.tags }}
        with:
          push: true
          targets: |
            ns-dashboard
            ns-sablier
          files: |
            ./docker-bake.hcl
            cwd://${{ steps.meta.outputs.bake-file-labels }}
            cwd://${{ steps.meta.outputs.bake-file-annotations }}
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
