name: Comment preview environment URL

on:
  # pull_request_target を使うにあたって https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ の一読を推奨
  pull_request_target:
    types:
      - opened

permissions:
  issues: write
  pull-requests: write

jobs:
  comment:
    name: Comment preview environment URL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const url = `https://${context.payload.pull_request.number}.ns-preview.trapti.tech/`
            const msg = `
            Preview (prod backend + PR dashboard) → ${url}
            `

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: msg
            });
