name: Preview

on:
  # pull_request_target を使うにあたって https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ の一読を推奨
  pull_request_target:

permissions:
  packages: write

jobs:
  image:
    name: Build preview images
    runs-on: ubuntu-latest
    steps:
      - name: Set PR_NUMBER env
        run: echo "PR_NUMBER=${{ github.event.number }}" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        id: buildx
      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: traptitech
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=sha
            type=raw,value=preview-${{ env.PR_NUMBER }}-${{ github.event.pull_request.head.sha }}
          sep-tags: ","

      - name: Build
        uses: docker/bake-action@v6
        env:
          APP_VERSION: ${{ env.APP_VERSION }}
          APP_REVISION: ${{ env.APP_REVISION }}
          TAGS: ${{ steps.meta.outputs.tags }}
        with:
          push: true
          targets: |
            ns-dashboard
            ns-sablier
          files: |
            ./docker-bake.hcl
            cwd://${{ steps.meta.outputs.bake-file-labels }}
            cwd://${{ steps.meta.outputs.bake-file-annotations }}
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
