name: Release Helm

on:
  push:
    tags:
      - helm/v*.*.*
    branches-ignore:
      - '**'

jobs:
  release-helm:
    name: Release Helm Chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: traptitech
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package chart
        run: |
          cd charts
          helm package neoshowcase

      - name: Publish chart
        run: |
          cd charts
          helm push neoshowcase-*.tgz oci://ghcr.io/traptitech/charts

  dispatch-renovate:
    name: Dispatch Renovate
    runs-on: ubuntu-latest
    needs:
      - release-helm
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.DISPATCH_PAT }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'traPtitech',
              repo: 'manifest',
              workflow_id: 'renovate.yaml',
              ref: 'main'
            })
