name: Renovate

permissions:
  contents: write

on:
  # For manual dispatch
  workflow_dispatch:
    inputs:
      dryRun:
        description: Dry-Run
        default: "false"
        required: false
      logLevel:
        description: Log-Level
        default: debug
        required: false
  # For auto-merge - should exclude non-renovate branch dispatches in job definitions below
  workflow_run:
    workflows:
      - CI
    types:
      - completed
  schedule:
    # 5 a.m. in JST(+9)
    - cron: "0 20 * * *"
  # For auto-merge and rebasing
  push:
    branches: ["main"]

env:
  LOG_LEVEL: debug
  RENOVATE_DRY_RUN: false
  RENOVATE_CONFIG_FILE: .github/renovate-bot.json5

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    # Exclude dispatch from non-renovate checks
    if: ${{ !(github.event_name == 'workflow_run' && !startsWith(github.event.workflow_run.head_branch, 'renovate/')) }}
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          app-id: ${{ secrets.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Override default config from dispatch variables
        shell: bash
        env:
          INPUT_DRY_RUN: ${{ github.event.inputs.dryRun }}
          INPUT_LOG_LEVEL: ${{ github.event.inputs.logLevel }}
        run: |
          echo "RENOVATE_DRY_RUN=${INPUT_DRY_RUN:-$RENOVATE_DRY_RUN}" >> "${GITHUB_ENV}"
          echo "LOG_LEVEL=${INPUT_LOG_LEVEL:-$LOG_LEVEL}" >> "${GITHUB_ENV}"
      - name: Renovate
        uses: renovatebot/github-action@693b9ef15eec82123529a37c782242f091365961 # v46.1.14
        with:
          renovate-image: "ghcr.io/renovatebot/renovate"
          renovate-version: "latest"
          configurationFile: "${{ env.RENOVATE_CONFIG_FILE }}"
          token: "${{ steps.generate-token.outputs.token }}"
