name: Renovate

permissions:
  contents: write

on:
  # For manual dispatch
  workflow_dispatch:
    inputs:
      dryRun:
        description: Dry-Run
        default: "false"
        required: false
      logLevel:
        description: Log-Level
        default: info
        required: false
  schedule:
    # 5 a.m. in JST(+9)
    - cron: "0 20 * * *"
  # For auto-merge and rebasing
  push:
    branches: ["main"]

concurrency:
  group: renovate
  cancel-in-progress: true

env:
  LOG_LEVEL: info
  RENOVATE_DRY_RUN: false
  RENOVATE_CONFIG_FILE: .github/renovate-bot.json5

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          app-id: ${{ secrets.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Override default config from dispatch variables
        shell: bash
        env:
          INPUT_DRY_RUN: ${{ github.event.inputs.dryRun }}
          INPUT_LOG_LEVEL: ${{ github.event.inputs.logLevel }}
        run: |
          echo "RENOVATE_DRY_RUN=${INPUT_DRY_RUN:-$RENOVATE_DRY_RUN}" >> "${GITHUB_ENV}"
          echo "LOG_LEVEL=${INPUT_LOG_LEVEL:-$LOG_LEVEL}" >> "${GITHUB_ENV}"
      - name: Renovate
        uses: renovatebot/github-action@b50d2ba2bd928235abdcc14d06dfafc217f1c565 # v46.1.18
        with:
          renovate-image: "ghcr.io/renovatebot/renovate"
          renovate-version: "latest"
          configurationFile: "${{ env.RENOVATE_CONFIG_FILE }}"
          token: "${{ steps.generate-token.outputs.token }}"
